  for ch = 1:size(image, 3)
    
    I_hat_zoom(:,:, ch)=[I_hat(1:W / 2, 1:H / 2, ch), ...
                    zeros(W / 2, nPadding(1)), ...
                    I_hat(1:W / 2, H / 2 +1 : H, ch)];
    
    I_hat_zoom(:,:, ch)=[I_hat_zoom(:,:, ch); zeros(nPadding(2), size(I_hat_zoom, 2))];
    
    I_hat_zoom(:,:, ch)=[I_hat_zoom(:, :, ch); I_hat(W / 2 + 1:H, 1:H/2, ch), ...
                    zeros(W / 2, nPadding(1)), ...
                    I_hat(W /2 +1:W, H / 2 + 1:H, ch)];    
  endfor      